---
- hosts: windows
  gather_facts: no

  tasks:
    - name: Test WinRM
      ansible.windows.win_ping:

    - name: Test shell
      ansible.windows.win_shell: hostname
      register: out

    - debug:
        var: out.stdout
